### PR TITLE
contact form margins fix style added to message

### PR DESCRIPTION
**Pull request by zalabhavy**
issue no #377 

I have give proper margins to contact form.
Also message seen after submit form give it css style for better looks.

image

### CODE REVIEW

**Comment by zalabhavy** [comment]
@Shubh942 please check it and merge !
Also provide labels to this PR.

**Comment by Shubh942** [comment]
Could you change the design to make it more attractive?

**Comment by zalabhavy** [comment]
@Shubh942 For that I will open another issue !

**Comment by zalabhavy** [comment]
@Shubh942 @HimanshuNarware Please check it and merge !

**Comment by zalabhavy** [comment]
@HimanshuNarware Please merge my this PR !

**Comment by PSS2134** [comment]
can you resolve the ui issue at about us section @zalabhavy

**Pull request closed without merging**
