### PR TITLE
Added Missing Images of Internships

### PR DESCRIPTION
**Pull request by SadafKausar2025**
fixed issue : #276 

before
Screenshot (1911)

after
Screenshot (1912)

before
Screenshot (1913)

after
Screenshot (1914)

before
Screenshot (1915)

after
Screenshot (1916)

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
hello @HimanshuNarware  and @Shubh942 
can you please review this PR and merge it

**Comment by HimanshuNarware** [comment]
@SadafKausar2025  share a 30 sec video

**Comment by SadafKausar2025** [comment]
https://github.com/HimanshuNarware/CareerZunction_Intern/assets/137484958/e4a50426-dc3d-4e9c-9152-0e2222279f1c

**Comment by SadafKausar2025** [comment]
hello @HimanshuNarware 
I have made vedios , there were 3 - 4 images of the internship was missing I corrected it

**Comment by SadafKausar2025** [comment]
hello @HimanshuNarware 
please give levels also

**Comment by SadafKausar2025** [comment]
Thank You

**Pull request merged**
