### PR TITLE
Add  more option on navbar

### PR DESCRIPTION
**Pull request by pandeyji711**
@HimanshuNarware Add more option related to the website
Screenshot 2024-05-15 004921

### CODE REVIEW

**Comment by pandeyji711** [comment]
@HimanshuNarware please review and merge

**Comment by pandeyji711** [comment]
@HimanshuNarware please label it Gssoc 2024

**Comment by PSS2134** [comment]
Which issue are you fixing @pandeyji711 ?

**Comment by pandeyji711** [comment]
@PSS2134 #40  please add label Gssoc 2024

**Comment by PSS2134** [comment]
@pandeyji711 This issue #40 is about adding icons , which cannot be seen ?

**Comment by pandeyji711** [comment]
@PSS2134 Now added fabicon and more options 

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/154527778/4b15d1d5-d47b-4042-91c5-b6ddff879575

**Comment by Shubh942** [comment]
Ensure there is adequate space between the icon and the text.

**Comment by pandeyji711** [comment]
@Shubh942 fixed spacing 
Screenshot 2024-05-17 132434
please review and merge with Gssoc24 and level tag

**Comment by PSS2134** [comment]
add some space between icon and text and also align them at same level  horizotally @pandeyji711

**Comment by pandeyji711** [comment]
> add some space between icon and text and also align them at same level horizotally

@PSS2134 fixed

**Comment by pandeyji711** [comment]
@HimanshuNarware please review and merge

**Comment by HimanshuNarware** [comment]
@pandeyji711 this is not responsive and effecting the responsiveness of the Web that why closing this PR

**Pull request closed without merging**
