### PR TITLE
✔️Implemented "Feedback Form" for CareerZunction!

### LINKED ISSUE #430: 💥Implement a Dedicated "Feedback Page" to CareerZunction!
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @PSS2134 ,

I  Want to implement a feedback form/page on the CodeHarbour website to gather user feedback and improve the Website services. 
The feedback form page should be accessible from the main navigation and allow users to provide their thoughts and suggestions easily.

### Here's What Will I Do 
- Form Fields **(Name, email, Rating, Feedback)**
- I Will **Add a "Modal" Button** On Clicking which the **Feedback Page will open** (for ex below)
- Additionally, will add a "Tooltip" for the modal feedback button.
- Will Ensure that **email field contains a valid email address.**
- **"Star Rating System" that must be between 1 and 5.**
- **The form will match the current website's design and aesthetics.**
- Provide a **thank you alert upon successful submission.**

**Here's Example of My Previous Work -**

https://github.com/user-attachments/assets/8105c34e-5dd0-4b8e-a2ea-b9d19ce8c66d

Please Assign me this issue

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @PSS2134 and @HimanshuNarware 
issue closes #430 

### Here's What I Did 
1. **Added a "modal button"** to open the feedback form.
2. **Implemented a "tooltip"** for it to enhanced user experience.
3. Created a **"dedicated feedback form"** following the **website's color theme.**
4. **Ensured "Responsiveness"** across all screen sizes.
5. **Implemented reset functionality** for the form.
6. **Added an alert for successful submission.**
7. **Implemented "Real Email Sending" Functionality** using Formspree

**Here as you can see -** 

https://github.com/user-attachments/assets/2bf52e3e-8470-4e8a-b347-8d30c1e46b04

**Here's the Email I received After submission -** 

image

If everything looks Good.
Here are the steps to follow to get the full access - 
1. **Create a free account** on formspree.io website.
2. **Create a New Form** named "CareerZunction FeedForm" 
3. Then you'll see the **`FORM ENDPOINT URL`** of that Newly created form.
4. **Share the `FORM ENDPOINT URL` with me**, So that I will Update the Code to your Credentials.

Please take a look and review it.

### CODE REVIEW

**Comment by aslams2020** [comment]
@PSS2134 @HimanshuNarware Please take a look

**Comment by PSS2134** [comment]
@aslams2020 Can you look at the code for contact us, there also we have the functionality of sending message to mails, you can implement that same thing here so that we dont need to do setup

**Comment by aslams2020** [comment]
@PSS2134 Oh ok, Sure, I will try to include that one here

**Comment by aslams2020** [comment]
@PSS2134 Done! Please check 

https://github.com/user-attachments/assets/f6905010-e60c-48a5-a155-b14e0844d5c9

**Comment by aslams2020** [comment]
@PSS2134 please check

**Comment by PSS2134** [comment]
Resolve the conflicts, and its getting delivered to mail right? @aslams2020

**Comment by aslams2020** [comment]
@PSS2134 Yes!

**Pull request merged**
