### PR TITLE
Hovering Effect Enhanced!!!

### PR DESCRIPTION
**Pull request by UjjwalGupta1105**
Fixes: #149 
I have enhanced the **Hovering effect** , please take a look.

### Before:
GSSOC 4

### After:
updated

### CODE REVIEW

**Comment by PSS2134** [comment]
Thats too much box shadow on hovering @UjjwalGupta1105

**Comment by UjjwalGupta1105** [comment]
Is it okk now??

hutler

Can I create a pull request now?

**Comment by PSS2134** [comment]
Yes @UjjwalGupta1105

**Comment by UjjwalGupta1105** [comment]
fixes:#149
All the changes are added now , you can now merge it .


hutler

**Comment by Shubh942** [comment]
Looks Good. @HimanshuNarware check it out.

**Comment by PSS2134** [comment]
Looks fine @UjjwalGupta1105 Good Work

**Comment by UjjwalGupta1105** [comment]
As the PR is already merged , you haven't assigned me the task ,

So please assign me the task so that the PR gets count in my Leaderboard .

**Pull request merged**
