### PR TITLE
Fixed sidebar in the mobile view

### LINKED ISSUE #453: [Feature Request]: footer in mobile view
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

fixing footer in mobile view 

### Use Case

footer enhancement 

### Benefits

_No response_

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by dhairyagothi**
closes #453 

fixed 
image

Please merge PR asap

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@PSS2134 please check and merge PR

**Comment by PSS2134** [comment]
Can you check, still the text overflows in that button @dhairyagothi

**Comment by dhairyagothi** [comment]
@PSS2134 sorry but my issue is regarding side bar so i have solved that issue only

**Comment by dhairyagothi** [comment]
I will raise another issue for fixing css of website in mobile view please merge this @PSS2134

**Comment by PSS2134** [comment]
> @PSS2134 sorry but my issue is regarding side bar so i have solved that issue only

sorry missed that, the sidebar looks fine, but the Back to Top button gets hidden, please check this

**Comment by dhairyagothi** [comment]
Okay fixing that now

**Comment by dhairyagothi** [comment]
image
 
 fixed @PSS2134  please merge PR

**Comment by PSS2134** [comment]
> image
> 
> fixed @PSS2134 please merge PR

Align back to top button with the left feedback button

**Comment by dhairyagothi** [comment]
image
@PSS2134  fixed

**Comment by dhairyagothi** [comment]
@PSS2134 please merge PR 31 july is last date for contributing PR

**Comment by dhairyagothi** [comment]
@PSS2134 please merge

**Comment by dhairyagothi** [comment]
@PSS2134 please merge

**Pull request merged**
