### PR TITLE
adding hover animation on card & button

### PR DESCRIPTION
**Pull request by ANSH127**
Issue34-Adding hover animations and glow and tilt animations in the CSS cards 

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/119344874/9eb276d4-0264-4235-854c-5a8609c5c7a5

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@ANSH127  not looking good,  don't make the hover effect so much aggressive

**Comment by ANSH127** [comment]
@HimanshuNarware okay let me fix it

**Comment by ANSH127** [comment]
@HimanshuNarware 
i updated the hover effect 

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/119344874/4fb549d9-0802-4122-870d-b93a0a54fc79

**Comment by HimanshuNarware** [comment]
@ANSH127 that looks great, do one thing make it lit bit more lite

**Comment by ANSH127** [comment]
@HimanshuNarware  done i had made the hover effect lite 

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/119344874/4cfd6520-c2de-4558-9f0a-e319ed5e2fc8

**Comment by HimanshuNarware** [comment]
@ANSH127  nice work, feel free to create more issues. also starred  our repo

**Pull request merged**
