### PR TITLE
improve hover in internship section 

### PR DESCRIPTION
**Pull request by Priyal208**
Under #451 assigned to me i improved hover effect, made the colors on hover more in sync with website them, made transiiton slow smoother and more attractive, earlier it looked very different and out of box, i made it more eye catchy and elegant.
You can see in the video

https://github.com/user-attachments/assets/9424f526-2501-4d25-9f15-77189ab9d839

### CODE REVIEW

**Comment by Priyal208** [comment]
@PSS2134 pls merge this asap

**Comment by Priyal208** [comment]
@PSS2134 pls look into this asap as PRs merged after 30 july wont be counted

**Comment by PSS2134** [comment]
the card grows much bigger in effect, make it a bit smaller compared to now, also the text in apply now button seems wrapped, you can fix that as well (align it in same line) @Priyal208

**Comment by Priyal208** [comment]
@PSS2134 ok sure ill do that by today

**Comment by Priyal208** [comment]
@PSS2134 now pls merge it asap, i did align the button now as requird also reduce the scale up , earlier it was by 10% now i did by 5%

**Comment by Priyal208** [comment]
https://github.com/user-attachments/assets/bb78b809-172d-49f8-b798-c3cb02a4acf2

it is scale down also button is aligned

**Comment by Priyal208** [comment]
the  code for button's color and css is in other pr so u dont worry about that

**Comment by Priyal208** [comment]
@PSS2134 pls merge it by today asap

**Comment by Priyal208** [comment]
@PSS2134 pls look into this PR immediately as PRs merged after today wont be counted for gssoc so pls look into this asap

**Pull request merged**
