### PR TITLE
Seach bar and filter feature

### PR DESCRIPTION
**Pull request by MitashaJ**
A search bar has been added to the top of the internship page. It can be used to search internships based on **Company name and Internship name both**.
image

A Filter feature is added at the right side of the search bar . It can be used to **filter results based on the mode of work**-online, offline, hybrid. (default-All modes)

image

### CODE REVIEW

**Comment by Shubh942** [comment]
Can you add fuzzy search functionality? 
Also specify the issue you are solving.

**Comment by MitashaJ** [comment]
yes sure @Shubh942 .

**Comment by PSS2134** [comment]
@MitashaJ , for results not found , the footer seems to get misplaced, also check that, keep the border color of searchbar as theme color

**Comment by MitashaJ** [comment]
okay  @PSS2134 ! i will update it in my new issue where I have added fuzzy search functionality - PR #211 .

**Comment by HimanshuNarware** [comment]
@MitashaJ resolve conflicts

**Comment by MitashaJ** [comment]
**Adding a search bar for company names and work mode-based filter option #211**
New PR has been created with fizzy search functionality ,responsive design and NO conflicts @HimanshuNarware

**Pull request closed without merging**
