### PR TITLE
Changed footer UI and made it responsive (issue#15)

### PR DESCRIPTION
**Pull request by AlaynaShaheen**
Now the footer is divided into 4 sections and the content in it is clearly visible now. Also @sarthak-stranger (another assignee) added a qr code to the footer section which has a video about internships and need of internships.
Desktop view:
Screenshot 2024-05-13 142607

Mobile view:
Screenshot 2024-05-13 142635
Screenshot 2024-05-13 142648

After scanning QR we will be redirected to a video about internships and also we can click on social media links in that video:
qr
This is the screenshot of video which has social media links in it too.

### CODE REVIEW

**Comment by sarthak-stranger** [comment]
View of screen When we scan QR.
https://github.com/HimanshuNarware/CareerZunction_Intern/assets/92575432/27770e91-f762-4f44-89eb-30e3a6a51f44

**Comment by HimanshuNarware** [comment]
> View of screen When we scan QR. https://github.com/HimanshuNarware/CareerZunction_Intern/assets/92575432/27770e91-f762-4f44-89eb-30e3a6a51f44

Good Work

**Comment by HimanshuNarware** [comment]
@AlaynaShaheen you did a wonderful job, also @sarthak-stranger nice job

**Comment by AlaynaShaheen** [comment]
@HimanshuNarware can you please add GSSoC'24 label...

**Comment by sarthak-stranger** [comment]
@HimanshuNarware Hi, Please add GSSOC24 tag also.

**Pull request merged**
