### PR TITLE
beautified about heading font,some lines font in docs page as well as corrected the font size of 'steps' in docs page

### PR DESCRIPTION
**Pull request by venkatasai24**
These are the changes I made.

image

image

I hope you would love to merge it @HimanshuNarware !!

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
feel free to create more issues, also starred our repo :)

**Comment by venkatasai24** [comment]
Kudos!!!

**Comment by venkatasai24** [comment]
I request you to add the necessary label to this issue (```level 1 and gssoc```) @HimanshuNarware

**Comment by venkatasai24** [comment]
Pls add the labels @HimanshuNarware

**Comment by HimanshuNarware** [comment]
> Pls add the labels @HimanshuNarware

mention issue number

**Comment by venkatasai24** [comment]
It's #22 @HimanshuNarware

**Comment by venkatasai24** [comment]
hey @HimanshuNarware ,this pr was not added in the leaderboard,pls resolve it asap

**Pull request merged**
