### PR TITLE
Add filters filters for new buttons to filter out the internships on the basis of role and industry

### PR DESCRIPTION
**Pull request by nikki-05**
Issue Fixes #478 

Added the new filter for sorting out the internships based on Role and Industry
-Made changes in the DataBase.json file according to the filters
-Updated the CSS portion to make filters according to the layout and style of the website
-Updated according to the earlier reviewed changes

Features:
-The filter shows default internships even without selecting any filter
-It filters out the internships when any role/ industry is selected 
-the style of the filter matches with the page 
Here is the attached image below :
Screenshot 2024-08-01 163438

### CODE REVIEW

**Comment by nikki-05** [comment]
Hello @HimanshuNarware can you review it now

**Comment by PSS2134** [comment]
Can you improve the ui of select tag, like spacing of options in drop down, colour and size of select tag, also show not found or something like that if no results available for selected option @nikki-05

**Comment by nikki-05** [comment]
> Can you improve the ui of select tag, like spacing of options in drop down, colour and size of select tag, also show not found or something like that if no results available for selected option @nikki-05

Sure sir

**Comment by nikki-05** [comment]
is it okay now?
or if any more changes are needed please do guide.

**Comment by PSS2134** [comment]
Fixes #418

**Pull request merged**
