### PR TITLE
Added the Authentication Functionality

### PR DESCRIPTION
**Pull request by ankitgupta143**
I added the authentication functionality like signup, login and logit with proper pop-up messages and handled the database in backend

### CODE REVIEW

**Comment by ankitgupta143** [comment]
@PSS2134 Kindly check and review it, merge the PR, It took 1 week to add authentication

**Comment by HimanshuNarware** [comment]
@ankitgupta143 Nice job, share a demonstration video of your changes (like how it works)

**Comment by HimanshuNarware** [comment]
@ankitgupta143  resolve  conflicts

**Comment by ankitgupta143** [comment]
@HimanshuNarware @PSS2134 I made a PR request, please check it.

**Comment by HimanshuNarware** [comment]
@ankitgupta143 Nice job, But do one thing again raise PR , and for now I am closing this PR

**Comment by ankitgupta143** [comment]
@HimanshuNarware @PSS2134 I again request you the PR request, please check it

**Pull request closed without merging**
