### PR TITLE
closes issue #210

### PR DESCRIPTION
**Pull request by AMISH-KHAN**
closes issue #210 

image

### CODE REVIEW

**Comment by PSS2134** [comment]
Can you check once for these 
Screenshot 2024-05-25 091327

**Comment by AMISH-KHAN** [comment]
What should I do here any suggestions?I can keep them in one line but that will break the over all look.

**Comment by PSS2134** [comment]
Instead of February, you can write feb or increase the width of the box to around 60% or something like that @AMISH-KHAN

**Comment by AMISH-KHAN** [comment]
I have made the requested changes

image

but dont know what do here

image

**Comment by Shubh942** [comment]
Looks Good @PSS2134 @HimanshuNarware

**Pull request merged**
