### PR TITLE
Feat/improve in founder and maintainer section

### PR DESCRIPTION
**Pull request by drick-infinity**
#293 Feat/interactive founder hover card See pull request #293

feat #188
updation on pull request #293
marked under gssoc'24
https://github.com/HimanshuNarware/CareerZunction_Intern/pull/293#issuecomment-2159119569

Screenshot (122)

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
Screenshot 2024-06-11 101502

keep a black background on the founder and maintainer page, also the name of the founder and maintainer is not visible

**Comment by drick-infinity** [comment]
Screenshot (124)


changes are done

**Comment by drick-infinity** [comment]
in above branch 

Feat/improve in founder and maintainer section #332

**Comment by HimanshuNarware** [comment]
@drick-infinity Nice Job

**Comment by drick-infinity** [comment]
mark label under gssoc'24

**Comment by drick-infinity** [comment]
@HimanshuNarware mark under gssoc'24 and mark level on it

**Comment by drick-infinity** [comment]
to show on leader boared

**Pull request merged**
