### PR TITLE
Fixed typo's in the README.md:

### PR DESCRIPTION
**Pull request by iemafzalhassan**
#### Hi @team
I have fixed some typos in the repo README.md file.
 

Screenshot 2024-05-16 at 4 49 30 PM

### CODE REVIEW

**Comment by PSS2134** [comment]
What issue are you fixing @iemafzalhassan !

**Comment by iemafzalhassan** [comment]
Hey @PSS2134 
I fixed type in the readme.md
In section #careerZunction there was a requirement to provide `space` and also enhanced type in contruting guide section.

**Comment by iemafzalhassan** [comment]
Hey @PSS2134 
Actually this issue is not defined in the issue section.
Should i create a new issue for this work ?

**Comment by HimanshuNarware** [comment]
@iemafzalhassan  resolve conflicts

**Comment by HimanshuNarware** [comment]
resolve conflicts

**Pull request merged**
