### PR TITLE
#34 added hover effects on internship page

### PR DESCRIPTION
**Pull request by IkramBagban**
This pull request adds subtle hover effects to the internship cards and buttons on the internship page, enhancing the user interface and improving visual feedback for users. The hover effects are designed to be lightweight and do not affect the page's performance.

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@IkramBagban  also share before and after screenshot

**Comment by IkramBagban** [comment]
@HimanshuNarware 

Before 
image


After[
image
](url)


The hover effect has a smooth transition, and the card also enlarges slightly on hover.

**Comment by HimanshuNarware** [comment]
@IkramBagban mention issue code /nu,ber

**Comment by IkramBagban** [comment]
I have mention above. Anyways, It is the solution of issue number #34

**Comment by IkramBagban** [comment]
@HimanshuNarware please first assign this to me then merge.

**Comment by HimanshuNarware** [comment]
@IkramBagban  Dont raise PR before gets Assigned, it messed up the code

**Pull request closed without merging**
