### PR TITLE
Added Preloader to website #326

### PR DESCRIPTION
**Pull request by dhairyagothi**
i have added the preloader to website please see to it and accept PR 
issue #326

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@dhairyagothi  share a 30 sec video

**Comment by dhairyagothi** [comment]
> @dhairyagothi  share a 30 sec video

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/142989448/eae94caa-989b-4b60-9452-9db33479f837

Preloader is working fine in desktop site 
But 
There is problem in CSS of website in mobile view 
Video is in mobile view .

**Comment by dhairyagothi** [comment]
https://github.com/HimanshuNarware/CareerZunction_Intern/assets/142989448/736aa247-ce76-4532-a2ee-e4e31744c1e5

please check this and merge the PR @HimanshuNarware

**Comment by HimanshuNarware** [comment]
@dhairyagothi  Preloader on mobile is not looking good try to improve that design

**Comment by dhairyagothi** [comment]
i have fixed this in mobile view @HimanshuNarware 

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/142989448/7fcfc421-f66a-48ef-91d2-cbed5ad07e19

please merge the PR with gssocc badge

**Comment by dhairyagothi** [comment]
please check and merge the PR @HimanshuNarware

**Comment by dhairyagothi** [comment]
@HimanshuNarware Sir please merge the PR with gssoc badge

**Comment by dhairyagothi** [comment]
@HimanshuNarware please merge the PR

**Comment by Shubh942** [comment]
Good work!

**Comment by dhairyagothi** [comment]
@Shubh942 @HimanshuNarware please assign this PR to me 

Please 🙏🏻

**Comment by dhairyagothi** [comment]
> Good work!

Please also Assign this PR to me

**Pull request merged**
