### PR TITLE
improve the overall visibility of the website

### PR DESCRIPTION
**Pull request by DevNandini02**
Updated the About Us section of the home page.

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@DevNandini02  share before and after screenshot, also resolved  conflics

**Comment by DevNandini02** [comment]
About Us section before.
before

After the changes.
after

**Comment by HimanshuNarware** [comment]
@DevNandini02  looking good , but add kind of tech related  background:

**Comment by DevNandini02** [comment]
> @DevNandini02 looking good , but add kind of tech related background:

I'll look into it sir and make changes asap.

**Comment by HimanshuNarware** [comment]
@DevNandini02  are you still working on this issue

**Pull request closed without merging**
