### PR TITLE
Added and Created Licensing Page Reflecting MIT License

### LINKED ISSUE #465: Add and Create a Licensing page Reflecting MIT License
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Hey @PSS2134 

I would like to add licensing page reflecting MIT License in footer on which under the repository and the website has license
To ensure clarity, Professionalism, Legal compliance.

image

Like this

image

Could you please assign this issue to me under Gssoc24?

### Suggested Change

N/A

### Rationale

_No response_

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by RadhikaMalpani1702**
Hey @PSS2134 

- issue closes #465 

I have added and created licensing page reflecting MIT license

image

Licensing Page: 

image

### CODE REVIEW

**Comment by RadhikaMalpani1702** [comment]
@PSS2134 Please merge this PR

**Comment by PSS2134** [comment]
Can you add a bit of spacing to b/w the paragraphs/ heading/ footer @RadhikaMalpani1702

**Comment by PSS2134** [comment]
Resolve conflicts, also add a screenshot @RadhikaMalpani1702

**Comment by RadhikaMalpani1702** [comment]
@PSS2134 Done

**Comment by RadhikaMalpani1702** [comment]
@PSS2134  Please take a look and review it

**Pull request merged**
