### PR TITLE
improve  ui of button

### PR DESCRIPTION
**Pull request by Priyal208**
Under #450 assigned to me , I improved Ui of buttons in internship section, I made it purple in theme with website, unlike earlier it was green and looked very out of theme

I aligned content in one line which looks better, I also added glow effect on hover which looks very attractive and appealing

In the below image  you can see both cases when it is under hover how it looks and how it looks normally
Screenshot 2024-07-26 135447

### CODE REVIEW

**Comment by Priyal208** [comment]
@PSS2134 kindly merge this

**Comment by PSS2134** [comment]
Can you use some other lighter color @Priyal208

**Comment by Priyal208** [comment]
@PSS2134 sure, if you have any specific color in mind, give me the hexcode

**Comment by PSS2134** [comment]
Please change color back to green also keep space between pagination thing and cards and footer @Priyal208

**Comment by Priyal208** [comment]
@PSS2134 ok sure ill do that by today

**Comment by Priyal208** [comment]
@PSS2134 kindly merge this, i changed to green and a lighter shade as you requested, the color now pops up and also looks subtle and classy unlike earlier green color which was very dull

U can see in both cases when it is under hover and when not----


Screenshot 2024-07-30 144846

**Comment by Priyal208** [comment]
@PSS2134 pls look into this PR immediately as PRs merged after today wont be counted for gssoc so pls look into this asap

**Pull request merged**
