### PR TITLE
Auto commenting feature added for merged prs

### LINKED ISSUE #218: Auto Commenting when a PR is merged
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

Could you please assign me this issue under GSSOC'24.

### PR DESCRIPTION
**Pull request by suhanipaliwal**
Closes #218

### CODE REVIEW

**Comment by Shubh942** [comment]
@HimanshuNarware looks good.
To make this functionality work, you need to add your GitHub token in repo secrets.

**Comment by suhanipaliwal** [comment]
Please add the labels of gssoc and level2 and assign me this pull request as per gssoc guidelines.

**Comment by suhanipaliwal** [comment]
Please merge this pull request.

**Comment by suhanipaliwal** [comment]
Please merge this pull request and add the necessary labels for gssoc.

**Pull request closed without merging**
