### PR TITLE
Navbar enhanced

### PR DESCRIPTION
**Pull request by H1mang1**

### CODE REVIEW

**Comment by Shubh942** [comment]
Please share a relevant video and image for reviewing purposes

**Comment by H1mang1** [comment]
Screenshot (248)
Screenshot (250)
Screenshot (247)
Screenshot (249)
Screenshot (246)

Uploading CareerZunction - Personal - Microsoft​ Edge 2024-05-14 20-16-52.mp4…

**Comment by H1mang1** [comment]
Uploading CareerZunction - Personal - Microsoft​ Edge 2024-05-14 20-16-52.mp4…

**Comment by H1mang1** [comment]
I have shared images but the video is taking time to upload.

**Comment by H1mang1** [comment]
As it taking time for the video to be uploaded here I have uploaded the video on YouTube.
Here's the link:
https://youtu.be/xPMn0eKHVhg?feature=shared

**Comment by PSS2134** [comment]
@H1mang1 I cant see , the hovering effect in video as that in the actual commit you have made! Can you check ?

**Comment by H1mang1** [comment]
> @H1mang1 I cant see , the hovering effect in video as that in the actual commit you have made! Can you check ?

I checked the code is same and also the hover effect is there too

**Comment by PSS2134** [comment]
Can you change the underline color to purple when we are at that page, otherwise white is fine

**Comment by H1mang1** [comment]
> Can you change the underline color to purple when we are at that page, otherwise white is fine

Okk
IMG_20240515_090458
I am facing issues in uploading the video here 
So I have uploaded it here
https://youtu.be/4DfxsdmpeDc

**Comment by PSS2134** [comment]
Good Job @H1mang1

**Comment by H1mang1** [comment]
> Good Job @H1mang1

Thank you so much

**Comment by H1mang1** [comment]
Please assign the labels

**Comment by H1mang1** [comment]
Thank you so much 🙏

**Pull request merged**
