### PR TITLE
made the paragraphs and headings on documentation page responsive

### PR DESCRIPTION
**Pull request by piyush-gpt**
made the paragraphs and headings on documentation page responsive

improving the UI and user experience

solves issue #104 

video

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/122816988/3d456ddf-eece-4219-91cc-aefb6aaba544

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@piyush-gpt SHARE A DEMO VIDEO

**Comment by piyush-gpt** [comment]
@HimanshuNarware   


https://github.com/HimanshuNarware/CareerZunction_Intern/assets/122816988/7afef6c2-c998-477a-ab12-fbc839bda386

**Comment by piyush-gpt** [comment]
@HimanshuNarware  please see

**Comment by HimanshuNarware** [comment]
@piyush-gpt  feel free to create more issues also starred our repo :)

**Pull request merged**
