### PR TITLE
✔️Improved UI of "FAQ Section" in the website 

### LINKED ISSUE #458: Feature🌟: Improvement in "FAQ Section" to the Website
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @HimanshuNarware  and @PSS2134 ,
here is the feature request that i want to suggest -

The current FAQ section of the website provides valuable information to users, but it could benefit from additional questions to address more common inquiries and improve the overall user experience.

I propose adding the more questions and answers to the FAQ section to make it more comprehensive and helpful.

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Tejashri-Taral**
Hey @HimanshuNarware and @PSS2134 
issue closes #458 

I have Improved the current FAQ Page in the website 
- Added more Comphrehensive Questions to it 
- Improved the Styling of Questions and Answers 
- Added Hovering Effects to it
- Added TextShadows to the headings.

https://github.com/user-attachments/assets/be9fd527-5ee1-4282-a11a-e884234c9d68

Please take a look.

### CODE REVIEW

**Comment by PSS2134** [comment]
This does not match website theme, Please make changes in the original theme, you can add more FAQs in that @Tejashri-Taral

**Comment by Tejashri-Taral** [comment]
@PSS2134 Done

**Comment by PSS2134** [comment]
Add a screenshot @Tejashri-Taral

**Comment by Tejashri-Taral** [comment]
@PSS2134 ,Okay

******Screenshot******
image

**Comment by Tejashri-Taral** [comment]
@PSS2134 ,Please take a look

**Comment by Tejashri-Taral** [comment]
@PSS2134 and @HimanshuNarware

**Comment by PSS2134** [comment]
Please revert to the original theme, just add questions in that, keep css as it is @Tejashri-Taral

**Pull request merged**
