### PR TITLE
Aligned the about us in home page

### PR DESCRIPTION
**Pull request by Riddhi162**
Fixed issue #434 
Aligned the about us in center

### CODE REVIEW

**Comment by PSS2134** [comment]
Can you add a bit more space at center @Riddhi162

**Comment by Riddhi162** [comment]
ok

**Comment by Riddhi162** [comment]
image
is this okay?

**Comment by PSS2134** [comment]
gap 60px looks good, also make it responsive @Riddhi162

**Comment by Riddhi162** [comment]
> gap 60px looks good, also make it responsive @Riddhi162

made the changes 
Screenshot 2024-07-23 181145

**Comment by PSS2134** [comment]
Good Work @Riddhi162

**Pull request merged**
