### PR TITLE
Changed navbar animations

### PR DESCRIPTION
**Pull request by Syed0206**
Demo Video is here have look once

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/123359660/3122d006-389b-461b-bb5b-666257d44d4d

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@Syed0206 keep the animation effect minimal, not that aggresive

**Comment by Syed0206** [comment]
Sir okay changed as per your instructions as design to minimal .Please review here is demo video .If you don't like this also please mention which type of design I should add please .

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/123359660/380dd043-217d-4fdd-9bb0-90b3029415f8

**Comment by HimanshuNarware** [comment]
@Syed0206 use left to right underline effect

**Comment by Syed0206** [comment]
Sur added underline effect Sir.Please review and merge my PR Sir.Here is demo video Sir.

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/123359660/22951f2e-4727-4861-92f3-0e88830a3285

**Pull request merged**
