### PR TITLE
Added Testimonials

### PR DESCRIPTION
**Pull request by sharmi4590**
Hey @HimanshuNarware 
Solved #170 
I have added the testimonials.
Screenshot (458)
Screenshot (459)
It displays text on hover.

### CODE REVIEW

**Comment by Shubh942** [comment]
Please resolve conflicts @sharmi4590

**Comment by Shubh942** [comment]
Looks good @PSS2134 @HimanshuNarware

**Comment by HimanshuNarware** [comment]
@sharmi4590 don't add testimonial on the home page,

**Comment by sharmi4590** [comment]
@HimanshuNarware Then where u want me to add it.?

**Comment by PSS2134** [comment]
@sharmi4590  Can you fix this

Screenshot 2024-06-10 205600

**Comment by HimanshuNarware** [comment]
> @HimanshuNarware Then where u want me to add it.?


In documentation section

**Pull request closed without merging**
