### PR TITLE
Add css to card 

### PR DESCRIPTION
**Pull request by pandeyji711**
Add hover effect to card that are benificial to reader with out go into the detail .

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/154527778/93faf28e-9f4b-4a88-824e-dd1d43341ee0

Screenshot 2024-05-12 150225

### CODE REVIEW

**Comment by pandeyji711** [comment]
@HimanshuNarware Please take a look at it; it looks awesome.

**Comment by HimanshuNarware** [comment]
@pandeyji711 doesn't match with the theme of the website.

**Comment by pandeyji711** [comment]
@HimanshuNarware can you suggest some!!

**Comment by HimanshuNarware** [comment]
> @HimanshuNarware can you suggest some!!

just use colors that match with the theme of the website.

**Comment by pandeyji711** [comment]
@HimanshuNarware please review
Screenshot 2024-05-12 172830

**Comment by pandeyji711** [comment]
@HimanshuNarware I think its looks good  and matched with theam
Screenshot 2024-05-12 180519

**Comment by pandeyji711** [comment]
@HimanshuNarware please review this

**Comment by pandeyji711** [comment]
I pushed the updated code to this branch , please review and merge

**Comment by HimanshuNarware** [comment]
@pandeyji711  your pr is messing with others code that why  I am closing this PR

**Pull request closed without merging**
