### PR TITLE
added wishlist functionality

### PR DESCRIPTION
**Pull request by rajat99-default**
here is solution of of the issue #107 
Now users will be able to add iternships to their wishlist 
we will create a seprate issue in which user will be able to remove the internships from wishlist

### CODE REVIEW

**Comment by PSS2134** [comment]
Looks good, but can you implement these @rajat99-default 

footer gets misplaced for wishlist section, if there are no wishlisted items present, also, 
add wishlisted items horizontally on wishlist section, and 
do not redirect on clicking the icon,
turn wishlist icons as marked on wishlist page and on clicking the icons again , remove it from the page.

**Comment by rajat99-default** [comment]
I will create a seperate issue

**Comment by rajat99-default** [comment]
First assign the Labels 
my previous PR is not counted in the leaderboards

**Comment by HimanshuNarware** [comment]
@rajat99-default  Resolve conflicts ,also make your design responsive for Mobile view

**Comment by rajat99-default** [comment]
design responsive for Mobile view
 
 is cheez pe ek alag se issue bana duga
 fir solve karluga

**Comment by Shubh942** [comment]
Conflict solve kardo.
Responsive bhi issi me kardo, alag issue banane ki koi jarurat nhi he iske regarding.

**Pull request closed without merging**
