### PR TITLE
hover effect on button within internship section

### PR DESCRIPTION
**Pull request by snehamalik09**
Adding hover effect on button within internship section - Used the same color as border, and have decreased the opacity as well. Please comment if anymore changes required. 

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/86192799/72f332e6-1791-4fe6-9dcd-4eb37d26d4eb

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@snehamalik09  the opacity of the color  is high , use low opacity in color

**Comment by snehamalik09** [comment]
> @snehamalik09 the opacity of the color is high , use low opacity in color


https://github.com/HimanshuNarware/CareerZunction_Intern/assets/86192799/406dcea2-b299-45ea-9c5e-5a44132cf0a3

opacity lower than this

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/86192799/4d26f690-18d0-4ddb-b7ac-559ed6676027

**Comment by HimanshuNarware** [comment]
@snehamalik09 feel free to create more issues, also starred our repo ;)

**Comment by snehamalik09** [comment]
> @snehamalik09 feel free to create more issues, also starred our repo ;)

sure sir

**Pull request merged**
