### PR TITLE
Amazon ML Summer School added

### PR DESCRIPTION
**Pull request by zalabhavy**
issue no #348

Information added with apply link and all needed details.

image

### CODE REVIEW

**Comment by zalabhavy** [comment]
@HimanshuNarware  Please check it and merge !

**Comment by Shubh942** [comment]
Good work!

**Comment by zalabhavy** [comment]
@Shubh942 Please also add labels so i get points.

**Comment by zalabhavy** [comment]
@Shubh942 @HimanshuNarware please provide labels otherwise my point will be not count.

**Comment by Shubh942** [comment]
Done

**Pull request merged**
