### PR TITLE
Add search Feature in Internship

### PR DESCRIPTION
**Pull request by Omi006**
I have solved the issue #102, have added the Search Feature in internship page.

Screenshot 2024-05-17 231437
 
image

### CODE REVIEW

**Comment by PSS2134** [comment]
Resolve Conflicts, also add not found or something like that , if there are no results when searched, @Omi006

**Comment by Shubh942** [comment]
Can you also add fuzzy search functionality?

**Comment by HimanshuNarware** [comment]
@Omi006 share  30 sec video , also remove conflicts

**Comment by Omi006** [comment]
https://github.com/HimanshuNarware/CareerZunction_Intern/assets/113918394/d2770b62-ad45-48db-8eae-e6f0fd8a2c4c


please review it!

**Pull request closed without merging**
