### PR TITLE
scroll bar added

### PR DESCRIPTION
**Pull request by spacedust26**
Scroll bar suiting the website added.
Files modified: Home.css

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@spacedust26  mention issue number/code

**Comment by spacedust26** [comment]
@HimanshuNarware sir, the issue number is #47

**Comment by HimanshuNarware** [comment]
@spacedust26  share a demo video

**Comment by PSS2134** [comment]
Looks Fine! @spacedust26

**Comment by spacedust26** [comment]
Thank you @PSS2134 and @HimanshuNarware !

**Comment by spacedust26** [comment]
@HimanshuNarware could you please assign labels to this PR

**Pull request merged**
