### PR TITLE
Added a dedicated "Terms and Conditions" Page

### LINKED ISSUE #463: [Feature Request]: Add a dedicated Terms and Conditions Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @PSS2134 

I would like to create a dedicatd Page for Terms and Conditions and add its link to the footer

image

### Use Case

Legel Compliance

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MastanSayyad**
Hey @PSS2134 

- Issue fixes #463

I have added dedicated Terms and conditions page and link it to the footer 

image

image

Please take a look and review it!

### CODE REVIEW

**Comment by MastanSayyad** [comment]
Hey @PSS2134 pls review this PR

**Comment by PSS2134** [comment]
Keep gap b/w all the points and a noticeable gap b/w last point and footer @MastanSayyad

**Comment by MastanSayyad** [comment]
> Keep gap b/w all the points and a noticeable gap b/w last point and footer @MastanSayyad

Okay I will do it right away!

**Comment by MastanSayyad** [comment]
Hey @PSS2134 I made the changes

image


image

**Pull request merged**
