### PR TITLE
Added wishlist functionality changed minor spelling mistakes

### PR DESCRIPTION
**Pull request by rajat99-default**

### CODE REVIEW

**Comment by PSS2134** [comment]
Can you heck the UI of wishlist icon (before and after) @HimanshuNarware, is it ok?

**Comment by rajat99-default** [comment]
We will create a separate issue for designing part
This issue was only for functionality

**Comment by rajat99-default** [comment]
Issue #106 and #107 solved under this

**Comment by PSS2134** [comment]
@rajat99-default Can you align all the cards horizontally in wishlist section , also make icon size on card bit larger and give some spacing from top and side, Is there any functionality to remove those cards from wishlist section , by again clicking those heart icons?

**Review by rajat99-default — COMMENTED** [review]
Resolved merge conflicts

**Pull request closed without merging**
