### PR TITLE
Create a New "Preloader" to the website 

### LINKED ISSUE #532: Create a New "Preloader" to the website
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @PSS2134 

I would like to add a new "preloader" for the website across all pages as the current one lags

### Use Case

N/A

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by MastanSayyad**
Hey @PSS2134 

- Issue Closes #532

I have created a new preloader for the website which matches the design theme 

- Created A new `Preloader.jsx` react component.
- Displays a `full-screen` preloader with a `#8e2de2` hue and increased `contrast`.
- The preloader `fades-out` smoothly after `2.5 seconds`.
- Integrated across all the pages for consistency.
- The video covers the entire `viewport` while maintaining its `aspect-ratio`.
- Made it completely `responsive`.

### Screen record
https://github.com/user-attachments/assets/c33f2566-4b43-47d3-88d2-d48226da13df

### Responsiveness

https://github.com/user-attachments/assets/6f646b61-6d30-43ef-a210-0fb023cd45ff

Additionally, I have to Re-Create a new scroll to top button as the previous one was in `index.html` breaking the functionality of the loader.
- Created a new `ScrollToTopButton.jsx` react component.
- The button is the radial gradient of `#4a00e0` and `#8e2de2`.
- On click it scroll backs to the top smoothly.
- Added `transform` and `hover` effects.
- Made it responsive.

https://github.com/user-attachments/assets/b4ec67ab-e8ef-4a02-82ed-153255eee124

Please take a look and review it, Thank you!

### CODE REVIEW

**Comment by PSS2134** [comment]
Can't see the loader when its deployed, can you check @MastanSayyad

**Comment by PSS2134** [comment]
Also looking at your efforts, changed it to level 3

**Comment by MastanSayyad** [comment]
> Can't see the loader when its deployed, can you check @MastanSayyad

At first due to so many load on the home page it may not seem but after a while it will work fine when you redirect to other pages 
Also try merging it and if in the deployed link it still didn't work then revert it back I will fix it!

The issue is with the Home.jsx and Index.html as it loads too much when we enter first

**Comment by MastanSayyad** [comment]
> Also looking at your efforts, changed it to level 3

Thank You, much appreciated!

**Comment by PSS2134** [comment]
> > Can't see the loader when its deployed, can you check @MastanSayyad
> 
> At first due to so many load on the home page it may not seem but after a while it will work fine when you redirect to other pages Also try merging it and if in the deployed link it still didn't work then revert it back I will fix it!
> 
> The issue is with the Home.jsx and Index.html as it loads too much when we enter first

ok lets see

**Comment by PSS2134** [comment]
Its not working now as well @MastanSayyad

**Comment by MastanSayyad** [comment]
Yeah, I see it too, let me fix it! I think I should remove the background black.

**Pull request merged**
