### PR TITLE
auto scroll to top added on new page render

### PR DESCRIPTION
**Pull request by paulkrishanu4**
Fixes: #277 

issue fixed

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/169196836/604165ab-eea4-4d9e-9692-e5238de396df

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@paulkrishanu4  feel free to create more issues, also starred our repo

**Comment by paulkrishanu4** [comment]
@HimanshuNarware kindly label this PR otherwise it will not be counted in leaderboard

**Comment by sanjay-kv** [comment]
@paulkrishanu4 add me into the repo, so i can fix label related issues.

**Comment by paulkrishanu4** [comment]
@sanjay-kv invitation send

**Pull request merged**
