### PR TITLE
added privacy policy page & made it responsive

### LINKED ISSUE #464: [Feature Request]: Add a Privacy Policy page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently, the website doesn't have a privacy policy page, I would like to create one

### Use Case

For assuring the privacy to the users

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Asymtode712**
## Description

Fixes #464 

- Created new `PrivacyPolicy` component for CareerZunction
- Added comprehensive privacy policy content specific to CareerZunction's internship platform
- Implemented responsive design for various screen sizes (768px, 425px, 375px, 320px)
- Styled component using a separate CSS file for better organization
- Ensured consistent branding with CareerZunction's color scheme
- Structured policy into clear sections for easy readability
- Included essential information on data collection, usage, sharing, and user rights

## Video

https://github.com/user-attachments/assets/71cc6ebe-5c30-49eb-b6a2-2aa793f62f18

### CODE REVIEW

**Comment by Asymtode712** [comment]
@PSS2134 please review and merge this PR

**Comment by PSS2134** [comment]
FAQ Section is affected, Please revert that @Asymtode712

**Comment by Asymtode712** [comment]
@PSS2134 I have resolved the merge conflicts

**Comment by Asymtode712** [comment]
@PSS2134 I have resolved all the nerge conflicts, kindly review and merge this PR

**Comment by PSS2134** [comment]
Please add a video @Asymtode712

**Comment by Asymtode712** [comment]
You may this the video below, the FAQ issue is also resolved now:

https://github.com/user-attachments/assets/254ab030-6b0a-46cc-b11a-f9717faa0193

**Pull request merged**
