### PR TITLE
Added missing image links in Internships box

### PR DESCRIPTION
**Pull request by SadafKausar2025**
Screenshot (1709)

Screenshot (1707)

Screenshot (1712)

Screenshot (1708)

there were more such missing image I updated all of them

### CODE REVIEW

**Comment by PSS2134** [comment]
Looks fine ! Mention the #issue  , will merge it @SadafKausar2025

**Comment by SadafKausar2025** [comment]
Can you please assign issue no #123 ?

**Comment by PSS2134** [comment]
@SadafKausar2025 This is pr no. what issue are you fixing but, mention that issue no.

**Comment by SadafKausar2025** [comment]
Can you please assign me this issue #156 ?
issue number is #156

**Comment by PSS2134** [comment]
Good Work @SadafKausar2025

**Comment by SadafKausar2025** [comment]
Thank You

**Comment by SadafKausar2025** [comment]
hello @PSS2134 
you have merge the PR but not given any level please give level to it
so that it can be counted in gssoc

**Pull request merged**
