### PR TITLE
enhanced footer

### PR DESCRIPTION
**Pull request by ayush-848**
# Fixes: #509

normal
image

for 768px
image

for 600px
image

### CODE REVIEW

**Comment by ayush-848** [comment]
@PSS2134 please check

**Comment by PSS2134** [comment]
> # Fixes: #509
> normal image
> 
> for 768px image
> 
> for 600px image

Here In mobile view, the careerZunction content in footer does not seem to be in center also its too seperated from below content, please fix that, also see if its responsive for tab view

**Comment by ayush-848** [comment]
> > # Fixes: #509
> > normal image
> > for 768px image
> > for 600px image
> 
> Here In mobile view, the careerZunction content in footer does not seem to be in center also its too seperated from below content, please fix that, also see if its responsive for tab view

can you give me a screen shot, so that i can know what will be the normal behavior

**Comment by PSS2134** [comment]
@ayush-848 I am talking about this one
Screenshot 2024-08-04 195416

**Comment by ayush-848** [comment]
> @ayush-848 I am talking about this one Screenshot 2024-08-04 195416

ok

**Comment by ayush-848** [comment]
image
@PSS2134

**Pull request merged**
