### PR TITLE
Footer modified

### PR DESCRIPTION
**Pull request by psychic-coder**
I have modified the footer, and have improved the ui . I have the added the hover effect's transitions . Improved the overall responsiveness of the website .

issue #82 

ScreenShots
Screenshot 2024-05-13 at 10 14 08 PM
Screenshot 2024-05-13 at 10 14 35 PM
Screenshot 2024-05-13 at 10 14 42 PM
Screenshot 2024-05-13 at 10 14 47 PM

### CODE REVIEW

**Comment by PSS2134** [comment]
Resolve the Conflicts please @psychic-coder

**Comment by psychic-coder** [comment]
I have resolved the conflicts @PSS2134

**Comment by PSS2134** [comment]
It is not responsive for desktop and Tabs @psychic-coder

**Comment by psychic-coder** [comment]
@PSS2134 you can check now , the error was because two div's had the same className , now It should work fine

**Comment by PSS2134** [comment]
@psychic-coder , the qr code thing is removed from footer, also the hover effect on icons does not seem good @

**Comment by psychic-coder** [comment]
@PSS2134 I just improved the hover effect of the icons , please check them and there what is the QR code thing I couldn't get that

**Comment by PSS2134** [comment]
You can check the current website has a QR code and Rateus

**Comment by psychic-coder** [comment]
@PSS2134 i have made the "rate us " section its the start in the follow us section , i'll add the qr and will  push it soon

**Comment by psychic-coder** [comment]
@PSS2134 i have added the qr .

**Comment by PSS2134** [comment]
Can you make equispaced the careerzunction and documenation heading at footer looks too close and resolve the conflicts @psychic-coder

**Comment by psychic-coder** [comment]
@PSS2134 actually all the the 5 cols are equally spaced , the heading of the careerzunction and documentation seem closer because of the size of the title careerzunction , if i'll try to increase the gap between them then I  have to shift the follow-us to the next line , and also I am unable to resolve the conflicts as its saying I don't have the write access

**Comment by PSS2134** [comment]
Pull the current changes to your local repo and then resolve conflicts and then commit it @psychic-coder

**Comment by psychic-coder** [comment]
I pushed the files but still I'm unable to resolve the conflicts , its saying

**Comment by psychic-coder** [comment]
I pushed the files @PSS2134  but still I can't resolve the conflicts
Screenshot 2024-05-26 at 6 45 01 PM

**Pull request closed without merging**
