### PR TITLE
Blog section is added into the website

### LINKED ISSUE #222: Add Blog Section to Navbar Featuring Student Internship Experiences
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To introduce a new blog section to the existing navigation bar on the website. This blog will feature posts from students who have secured internships through our platform, sharing their experiences and insights. This addition aims to build a sense of community, provide valuable information, and inspire other users

### Use Case

Adding a blog feature to the project significantly enhances its utility and value by increasing user engagement, building a community, providing valuable insights, improving SEO, showcasing platform success, supplying content for marketing, and encouraging user-generated content. This feature makes the platform more interactive, informative, and appealing to a broader audience, ultimately contributing to its growth and success.

### Benefits

_No response_

### Add ScreenShots

Existing navbar
Screenshot 2024-05-23 110223

after blog section(will work properly once it is assigned)

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/143430142/86eea888-6e1f-4012-8e09-af3e2c095d70

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Srujitha-Raghava**
close #222 

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/143430142/dc5b629d-a505-4ec9-b044-bd702d802ffb

### CODE REVIEW

**Comment by Srujitha-Raghava** [comment]
hey @HimanshuNarware kindly,please review the PR.

**Comment by HimanshuNarware** [comment]
@Srujitha-Raghava  not responsive,

**Comment by Srujitha-Raghava** [comment]
Heyy @HimanshuNarware!
I wanted to inform you that the changes you requested have been implemented. 
The blog section is now designed to be responsive and is visible only on desktop screens. 
Please review the changes and let me know if there are any further adjustments needed.
Thankyouu!!

**Comment by HimanshuNarware** [comment]
repo
@Srujitha-Raghava remove those empty icons that are present in the Mobile view for the blog section, also there is an infinite loop running in the console log also fix those

**Comment by Srujitha-Raghava** [comment]
@HimanshuNarware kindly review the changes

**Comment by Srujitha-Raghava** [comment]
@HimanshuNarware ??plz add the labels and assign the pr to me

**Comment by Srujitha-Raghava** [comment]
@HimanshuNarware ??

**Pull request merged**
