### PR TITLE
Issue86 functional theme change button

### PR DESCRIPTION
**Pull request by ANSH127**
add a feature to toggle the theme

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/119344874/97f7ce18-d546-4216-adc0-34096fed2334

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@ANSH127 RESOLVE CONFLICTS

**Comment by ANSH127** [comment]
@HimanshuNarware  Done

**Comment by HimanshuNarware** [comment]
@ANSH127 light theme has lots of problems like the font are not visible clearly. also internship section need improvement

**Comment by HimanshuNarware** [comment]
> add a feature to toggle the theme
> 
>  CareerZunction.-.Google.Chrome.2024-05-13.16-15-35.mp4
like you show in video font are not that in color

**Comment by ANSH127** [comment]
@HimanshuNarware  let me fix the font issue and tell me in light theme what changes you want.?

**Comment by ANSH127** [comment]
@HimanshuNarware 
Screenshot (205)

could I make the card bg light black?

**Comment by ANSH127** [comment]
I fixed the font issue and changed the bg color of the card 

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/119344874/b4fdee9a-25ce-4582-b9be-79adcee9b6ce

**Comment by HimanshuNarware** [comment]
@ANSH127 footer section text is not visible

**Comment by ANSH127** [comment]
@HimanshuNarware 
Now is it ok?
Screenshot (207)

**Comment by ANSH127** [comment]
done

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/119344874/8a86d2a4-ed41-41a4-ad10-2f4d17647414

**Comment by ANSH127** [comment]
@HimanshuNarware  


https://github.com/HimanshuNarware/CareerZunction_Intern/assets/119344874/9f9d1ee8-c05a-43a2-8acc-3fcf724f385b

**Comment by PSS2134** [comment]
Can you make hover effect in light theme to dark purple not black @ANSH127 ?

**Comment by ANSH127** [comment]
@PSS2134  okay sure

**Comment by ANSH127** [comment]
@PSS2134  done 

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/119344874/36e84723-25f6-466b-a70b-ddb950f4f076

**Comment by PSS2134** [comment]
In the Internship section, for light theme, the cards look too bright at borders, also the footer is not distinguishable , may be you can add a light grey line or something and keep the default theme to dark, when someone opens the site

**Comment by ANSH127** [comment]
@PSS2134 I have set the border gray on the light theme , distinguished the footer, and set by default the dark theme


Uploading CareerZunction - Google Chrome 2024-05-19 14-55-47.mp4…

**Comment by PSS2134** [comment]
Still looks bright and can't see gray line at the footer can you check @ANSH127

**Comment by HimanshuNarware** [comment]
@ANSH127  are you still  working on this issue.

**Comment by HimanshuNarware** [comment]
@ANSH127  for the light theme use a black background on the card, but  for the dark it is the same

**Comment by HimanshuNarware** [comment]
> @HimanshuNarware
> 
> Screenshot (206)
> 
> could I make the card bg light black?

@ANSH127 only for the light theme , dark theme remain same

**Comment by HimanshuNarware** [comment]
@ANSH127  Do one thing again raise PR with  recommended changes

**Pull request closed without merging**
