### PR TITLE
Fixed spelling of component from componet

### PR DESCRIPTION
**Pull request by rajat99-default**
After trying 3 days 
this is my last try to fix this issue
please approve my pr

this fixes issue #106

### CODE REVIEW

**Comment by rajat99-default** [comment]
@HimanshuNarware

**Comment by PSS2134** [comment]
Resolve Conflicts @rajat99-default

**Comment by rajat99-default** [comment]
Wait i am trying

**Comment by rajat99-default** [comment]
wait don't close pull request I am trying to solve it

**Comment by rajat99-default** [comment]
I have successfully resolved merge conflicts
@PSS2134

**Comment by PSS2134** [comment]
can you resolve for footer files? @rajat99-default

**Comment by rajat99-default** [comment]
resolved @PSS2134

**Comment by PSS2134** [comment]
Good Work! @rajat99-default

**Pull request merged**
