### PR TITLE
aligned-about-us-section

### PR DESCRIPTION
**Pull request by sooraj-reddy**
As per the raised issue 96:

Final output:
>The contents in the 'about us' section of home page are now aligned with corresponding elements: icon, data, card.
>Equal and uniformity between icons and data across all data-cards.

### CODE REVIEW

**Comment by PSS2134** [comment]
@sooraj-reddy The footer looks changed from that in actual website, can you revert that!, also share a video for that

**Comment by PSS2134** [comment]
Can you reduce the box size (padding) ? @sooraj-reddy

**Comment by sooraj-reddy** [comment]
https://github.com/HimanshuNarware/CareerZunction_Intern/assets/108564825/22f4eeee-fe18-44d6-8c80-820c1056b91a

**Comment by PSS2134** [comment]
Good Work @sooraj-reddy

**Comment by sooraj-reddy** [comment]
Thank you.

**Pull request merged**
