### PR TITLE
Changes to card design

### PR DESCRIPTION
**Pull request by Ishmeetkaur36**
#175

### CODE REVIEW

**Comment by HimanshuNarware** [comment]
@Ishmeetkaur36  share a before and after ss

**Comment by Ishmeetkaur36** [comment]
Screenshot 2024-06-05 133806
before



Screenshot 2024-06-05 133954
after

**Comment by Ishmeetkaur36** [comment]
Do you want any further changes to be made to this

**Comment by HimanshuNarware** [comment]
@Ishmeetkaur36

**Pull request closed without merging**
