### PR TITLE
added scroll to top button

### PR DESCRIPTION
**Pull request by reshamsai150**
closes: #158

image

I have added the  sticky scroll to top feature button in the website

### CODE REVIEW

**Comment by Shubh942** [comment]
@reshamsai150 can you please specify the issue you are solving.

**Comment by reshamsai150** [comment]
I have added the sticky scroll to top feature button in the website

**Comment by HimanshuNarware** [comment]
@reshamsai150 feel free to create more issus also starred our rep0 :)

**Comment by reshamsai150** [comment]
@HimanshuNarware  please assign level labels please  for the pull request

**Pull request merged**
