### PR TITLE
Trailing Cursor

### PR DESCRIPTION
**Pull request by Chandu6702**
closes : #335 

I have created a custom cursor. later I added a trailing effect to the custom cursor. And also updated CSS styles for optimal user experiences. 

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/125206920/edd63cac-4f8c-47ca-88ca-c405be826c45

### CODE REVIEW

**Comment by Chandu6702** [comment]
@HimanshuNarware please review and merge this PR

**Comment by Chandu6702** [comment]
@HimanshuNarware please review and merge this PR

**Comment by Shubh942** [comment]
Can you change the cursor to pointer type when it hovers over the clickable button?

**Comment by Chandu6702** [comment]
@Shubh942 I have updated the cursor please review it


https://github.com/HimanshuNarware/CareerZunction_Intern/assets/125206920/33e2e007-b81b-46b2-961d-cb0ded9daeef

**Comment by Shubh942** [comment]
Also add the I type cursor when text field is hovered.

**Comment by Shubh942** [comment]
You can see it on contact us page.

**Comment by Chandu6702** [comment]
@Shubh942 I have updated the cursor please review it and if it aligns with the changes requested then merge the PR.

https://github.com/HimanshuNarware/CareerZunction_Intern/assets/125206920/ba21afda-0912-42c9-a4c4-c92131607578

**Comment by Chandu6702** [comment]
@Shubh942 please review this PR

**Pull request closed without merging**
