### PR TITLE
Issue:183 - improved the footer button UI for the mobile view.

### PR DESCRIPTION
**Pull request by Shelbybosss**
added better values for transparency hovering effect adjusted z-index's of elements so that all are at their suitable places.

### CODE REVIEW

**Comment by Shubh942** [comment]
specify the issue you are solving

**Comment by Shelbybosss** [comment]
The sidebar buttons icons at the bottom on mobile view were unclear and not look good, as mentioned in issue 183. Also some part was not properly indexed it was overlapping so adjusted it's z-index.

**Comment by Shubh942** [comment]
Also add some images for reviewing

**Comment by Shelbybosss** [comment]
Before: 
before


After:
after

**Comment by Shelbybosss** [comment]
@HimanshuNarware do merge it

**Comment by HimanshuNarware** [comment]
> @HimanshuNarware do merge it

@Shelbybosss @Shubh942  resolve conflics

**Comment by HimanshuNarware** [comment]
> Before: before
> 
> After: after

@Shelbybosss  keep the background icons transparent

**Comment by Shelbybosss** [comment]
Transparent does not look good, the opacity is less which does the work

**Comment by HimanshuNarware** [comment]
> Transparent does not look good, the opacity is less which does the work

@Shelbybosss  ok

**Comment by Shubh942** [comment]
@Shelbybosss you need to resolve the conflicts.

**Comment by HimanshuNarware** [comment]
@Shelbybosss  do one thing change the opacity of the icon background, and show me

**Pull request closed without merging**
