### PR TITLE
[FEAT]: Created Issue forms and made the issue options more visually appealing

### PR DESCRIPTION
**Pull request by TonyStark-47**
This PR fixes the issue #95

### CODE REVIEW

**Comment by PSS2134** [comment]
Can you post the screenshot of preview of each of the .md files you have made changes into @TonyStark-47

**Comment by TonyStark-47** [comment]
Hey @PSS2134, here are the screenshots:

image
image
image
image
image
image
image
image

**Comment by PSS2134** [comment]
Looks good! Great Job @TonyStark-47

**Comment by TonyStark-47** [comment]
Hey @PSS2134, please put 'gssoc' label. Thank you.

**Pull request merged**
