### PR TITLE
Modified "Star us" in the footer 

### PR DESCRIPTION
**Pull request by sau-mili**
Changed the button text and modified the CSS for better readability as well as design.[#146 ](url)

### CODE REVIEW

**Comment by sau-mili** [comment]
fixes #146

**Comment by PSS2134** [comment]
can you change color of rateus to purple (original) and don't add hover on blue box, add just on rate us text @sau-mili

**Comment by sau-mili** [comment]
Okay i will change those and mention here

**Comment by sau-mili** [comment]
You can check it now @HimanshuNarware 
Screenshot 2024-05-19 110725

**Comment by sau-mili** [comment]
@HimanshuNarware please check and merge this.. I have been waiting for days :(

**Comment by PSS2134** [comment]
Ok good Work @sau-mili

**Comment by sau-mili** [comment]
Can you please add the gssoc and level labels?

**Pull request merged**
