### PR TITLE
enhancement of home page

### PR DESCRIPTION
**Pull request by Soumya6Tiwari**
Removed the bug and enhanced the home page .
image
@HimanshuNarware kindly review the pr

### CODE REVIEW

**Comment by PSS2134** [comment]
Good Work @Soumya6Tiwari !

**Comment by Soumya6Tiwari** [comment]
@PSS2134  kindly provide the gssoc tag and its level for this pull request as it is already merged .

**Comment by HimanshuNarware** [comment]
> @PSS2134 kindly provide the gssoc tag and its level for this pull request as it is already merge.

mention issue number or code

**Comment by PSS2134** [comment]
Issue #128

**Pull request merged**
