### PR TITLE
Adding a search bar for company names and work mode-based filter option 

### PR DESCRIPTION
**Pull request by MitashaJ**
[Feature Request]: Adding a search bar for company names and work mode-based filter option #197

A search bar has been added to the top of the internship page. It can be used to search internships based on **Company name and Internship name both.**
image

A Filter feature is added at the right side of the search bar . It can be used to **filter results based on the mode of work**-online, offline, hybrid. (default-All modes)

image

Fuzzy search functionality has been added and a threshold value set to 0.3 for a balanced level of fuzziness. 
image

### CODE REVIEW

**Comment by MitashaJ** [comment]
[Feature Request]: Adding a search bar for company names and work mode-based filter option #197 
https://github.com/HimanshuNarware/CareerZunction_Intern/issues/197
 
 Fuzzy search functionality has been added and a threshold value set to 0.3 for a balanced level of fuzziness. @Shubh942

**Comment by MitashaJ** [comment]
@PSS2134  I have fixed footer issue for 'No results' and updated border colour of search bar, filter.

image

The pagination currently doesn't display the default 12 internships as expected. As for search, it need to search through all internships, not just those on the current page. To fix this, pagination logic is needed to adjust. So should I change pagination logic or leave it be?

**Comment by MitashaJ** [comment]
The **pagination issue** has been fixed. Now, by **default, 12** internships are shown. When using the search or filter functions, the **maximum** number of internships shown is also **limited to 12.**

@PSS2134 u can now review it and also can u add labels to this PR ?

image


image

**Comment by Shubh942** [comment]
@HimanshuNarware review this pr.
Looks good to me.

**Review by HimanshuNarware — COMMENTED** [review]
@Shubh942  everything is ok, but do one thing call someone who can make this design more responsive.
Screenshot 2024-05-23 192202

**Review by PSS2134 — CHANGES_REQUESTED** [review]
@MitashaJ Can you make it responsive, for result not found and other cases, the font size for dropdown section also looks larger for mobile devices

**Comment by MitashaJ** [comment]
I have made the page responsive. @PSS2134 

WhatsApp Image 2024-05-29 at 14 40 01_ff2b0e3f

WhatsApp Image 2024-05-29 at 14 40 32_190cdd34

**Comment by MitashaJ** [comment]
@PSS2134 Can you review  and tell me if any other changes are required

**Comment by Shubh942** [comment]
@PSS2134 @HimanshuNarware looks good.

**Comment by MitashaJ** [comment]
@HimanshuNarware  can you just add lables to this PR ?

**Pull request merged**
